### PR TITLE
WIP: compile with ZIO 2.0.0-M3

### PR DESCRIPTION
**Pull request by vlushn**
This is obviously incomplete and I apologise if this PR shouldn't have been opened. However, I saw no build for ZIO 2.0.0-M3. What is the plan for providing one - will there be a 2.0 release of this library for ZIO 2, and should I continue fixing the deprecation warnings here?

### CODE REVIEW

**Comment by tusharmath** [comment]
Thanks @vlushn This is going to be great addition to the library!

**Comment by Methrat0n** [comment]
I would love this to land as I cant update easily ZIO to 2.0.0.
As of now I get this error : 

[error] (run-main-1) java.lang.NoSuchMethodError: 'zio.ZManaged zio.ZIO.toManaged(scala.Function1)'
[error] java.lang.NoSuchMethodError: 'zio.ZManaged zio.ZIO.toManaged(scala.Function1)'
[error] 	at zhttp.service.EventLoopGroup$Live$.make(EventLoopGroup.scala:30)
[error] 	at zhttp.service.EventLoopGroup$Live$.kQueue(EventLoopGroup.scala:36)
[error] 	at zhttp.service.EventLoopGroup$Live$.auto(EventLoopGroup.scala:45)
[error] 	at zhttp.service.EventLoopGroup$.auto(EventLoopGroup.scala:18)
[error] 	at zhttp.service.Server$.start(Server.scala:62)
[error] 	at com.memoranda.gateway.Main$.run(Main.scala:29)
[error] 	at zio.ZApp.$anonfun$main$1(ZApp.scala:60)
[error] 	at zio.Runtime.unsafeRunWith(Runtime.scala:311)
[error] 	at zio.Runtime.defaultUnsafeRunSync(Runtime.scala:89)
[error] 	at zio.Runtime.defaultUnsafeRunSync$(Runtime.scala:86)
[error] 	at com.memoranda.gateway.Main$.defaultUnsafeRunSync(Main.scala:14)
[error] 	at zio.Runtime.unsafeRunSync(Runtime.scala:84)
[error] 	at zio.Runtime.unsafeRunSync$(Runtime.scala:83)
[error] 	at com.memoranda.gateway.Main$.unsafeRunSync(Main.scala:14)
[error] 	at zio.Runtime.unsafeRun(Runtime.scala:66)
[error] 	at zio.Runtime.unsafeRun$(Runtime.scala:65)
[error] 	at com.memoranda.gateway.Main$.unsafeRun(Main.scala:14)
[error] 	at zio.ZApp.main(ZApp.scala:60)
[error] 	at zio.ZApp.main$(ZApp.scala:56)
[error] 	at com.memoranda.gateway.Main$.main(Main.scala:14)
[error] 	at com.memoranda.gateway.Main.main(Main.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 1 s, completed 27 Sept 2021, 16:01:41

Thx for your work :D

**Comment by tusharmath** [comment]
closing in fav of #645
